### ISSUE TITLE
Support for SSH access to chart repositories

### ISSUE THREAD

**Issue by edshelton** [stefanprodan/hrval-action#20]
`fatal: unable to access '***git@github.com:my-org/my-chart-repo/': URL using bad/illegal format or missing URL`

I use a GitHub repo as my chart repository in all my HelmRelease manifests, like this:

```
spec:
  chart:
    git: git@github.com:my-org/my-chart-repo
    path: my-chart
    ref: master
```

I'd rather not switch to `https://` if I can avoid it. I guess this would be a feature request?
